/**
 * UI Build Script
 * Bundles the React app and CSS for production
 */

import { mkdir } from "node:fs/promises";
import { join } from "node:path";

const srcDir = import.meta.dir;
const distDir = join(srcDir, "dist");

async function build() {
  console.log("Building UI...");

  // Ensure dist directory exists
  await mkdir(distDir, { recursive: true });

  // Build CSS with Tailwind CLI v4
  console.log("  Building CSS...");
  const cssResult = Bun.spawnSync([
    "bunx",
    "@tailwindcss/cli",
    "-i",
    join(srcDir, "globals.css"),
    "-o",
    join(distDir, "styles.css"),
    "--minify",
  ]);

  if (cssResult.exitCode !== 0) {
    console.error("CSS build failed:");
    console.error(cssResult.stderr.toString());
    process.exit(1);
  }

  // Bundle the React app
  console.log("  Building JS...");
  const result = await Bun.build({
    entrypoints: [join(srcDir, "main.tsx")],
    outdir: distDir,
    naming: "app.js",
    minify: true,
    sourcemap: "external",
    target: "browser",
    define: {
      "process.env.NODE_ENV": '"production"',
    },
  });

  if (!result.success) {
    console.error("JS build failed:");
    for (const log of result.logs) {
      console.error(log);
    }
    process.exit(1);
  }

  // Generate index.html
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Katana Dashboard</title>
  <link rel="stylesheet" href="/styles.css">
</head>
<body class="bg-background text-foreground">
  <div id="root"></div>
  <script type="module" src="/app.js"></script>
</body>
</html>`;

  await Bun.write(join(distDir, "index.html"), html);

  // Read the built files
  const cssContent = await Bun.file(join(distDir, "styles.css")).text();
  const jsContent = await Bun.file(join(distDir, "app.js")).text();

  // Generate embedded assets module for compile-time inclusion
  const embeddedModule = `// Auto-generated by build.ts - DO NOT EDIT
// This file embeds UI assets for the compiled binary

export const embeddedAssets = {
  "index.html": ${JSON.stringify(html)},
  "styles.css": ${JSON.stringify(cssContent)},
  "app.js": ${JSON.stringify(jsContent)},
} as const;

export type AssetName = keyof typeof embeddedAssets;
`;

  await Bun.write(join(srcDir, "embedded-assets.ts"), embeddedModule);

  console.log("Build complete! Output in src/ui/dist/");
  console.log("  Generated embedded-assets.ts for compiled binary");
}

build();
