services:
  musashi:
    image: ghcr.io/samuraiwtf/musashi-js:latest
    networks:
      - katana-net
    environment:
      - USE_TLS=true
      - CORS_CLIENT_PORT=3021
      - CORS_CLIENT_HOST=cors.test
      - CORS_API_PORT=3020
      - CORS_API_HOST=api-cors.test
      - CORS_API_PROXY_PORT=443
      - CSP_APP_PORT=3041
      - JWT_PORT=3050
      - JWT_HOST=jwt.test

networks:
  katana-net:
    external: true
