name: Full Test Suite

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'setup.py'
      - '.github/workflows/**'
      - 'test/**'
    branches: [ main ]
  pull_request:
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'setup.py'
      - '.github/workflows/**'
      - 'test/**'
    branches: [ main ]

jobs:
  collect-all-tests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          # Get all test scripts except test-all.sh
          TESTS=$(ls test/test-*.sh | grep -v test-all.sh | sed 's/.*test-\(.*\)\.sh/\1/' | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix={\"package\":$TESTS}" >> $GITHUB_OUTPUT

  run-tests:
    needs: collect-all-tests
    uses: ./.github/workflows/package-test.yaml
    strategy:
      matrix: ${{fromJson(needs.collect-all-tests.outputs.matrix)}}
      fail-fast: false  # Continue running other tests even if one fails
      max-parallel: 6   # Limit parallel jobs to avoid resource constraints
    with:
      package-name: ${{ matrix.package }}
