name: Module Tests

on:
  push:
    paths:
      - 'modules/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'modules/**'
    branches: [ main ]

jobs:
  check-full-tests:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: check
        run: |
          # Check if any paths that trigger full tests were changed
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            FULL_TEST_CHANGES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '\.py$|requirements.txt|setup.py|\.github/workflows/|test/' || true)
          else
            FULL_TEST_CHANGES=$(git diff --name-only HEAD^ HEAD | grep -E '\.py$|requirements.txt|setup.py|\.github/workflows/|test/' || true)
          fi
          
          if [ -z "$FULL_TEST_CHANGES" ]; then
            echo "Full test suite not triggered, should run module tests"
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "Full test suite will run, skipping module tests"
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  determine-tests:
    needs: check-full-tests
    if: needs.check-full-tests.outputs.should-run == 'true'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for comparing changes
          
      - id: set-matrix
        run: |
          # Get changed files in modules directory
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '^modules/' || true)
          else
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '^modules/' || true)
          fi
          
          # Extract specific tool/target names from paths
          # Example: modules/tools/zap.yml -> zap
          COMPONENTS=$(echo "$CHANGED_FILES" | sed -n 's|^modules/[^/]*/\([^/]*\)\..*|\1|p' | sort -u)
          
          # Build matrix JSON
          PACKAGES="["
          FIRST=true
          for COMPONENT in $COMPONENTS; do
            if [ -f "test/test-${COMPONENT}.sh" ]; then
              if [ "$FIRST" = true ]; then
                FIRST=false
              else
                PACKAGES="$PACKAGES,"
              fi
              PACKAGES="$PACKAGES\"$COMPONENT\""
            fi
          done
          PACKAGES="$PACKAGES]"
          
          # If no valid test files found, run all tests
          if [ "$PACKAGES" = "[]" ]; then
            PACKAGES='["all"]'
          fi
          
          echo "matrix={\"package\":$PACKAGES}" >> $GITHUB_OUTPUT

  run-tests:
    needs: [check-full-tests, determine-tests]
    if: needs.check-full-tests.outputs.should-run == 'true'
    uses: ./.github/workflows/package-test.yaml
    strategy:
      matrix: ${{fromJson(needs.determine-tests.outputs.matrix)}}
      fail-fast: false
    with:
      package-name: ${{ matrix.package }}
