name: Reusable workflow for testing packages

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      ubuntu-version:
        required: false
        type: string
        default: '22.04'

jobs:
  test:
    runs-on: ubuntu-${{ inputs.ubuntu-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup test environment
        run: sudo ./test/provision-ubuntu.sh

      - name: Run tests
        run: sudo ./test/test-${{ inputs.package-name }}.sh
