name: Reusable workflow for testing package installs

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: setup
        run: sudo ./test/provision-ubuntu.sh

      - name: verify
        run: sudo ./test/test-${{ inputs.package-name }}.sh
